//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCalcWinClient.CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcService.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/PerformOperation", ReplyAction="http://tempuri.org/ICalcService/PerformOperationResponse")]
        string PerformOperation(string operandA, string operandB, char op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/PerformOperation", ReplyAction="http://tempuri.org/ICalcService/PerformOperationResponse")]
        System.Threading.Tasks.Task<string> PerformOperationAsync(string operandA, string operandB, char op);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : WCFCalcWinClient.CalcService.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<WCFCalcWinClient.CalcService.ICalcService>, WCFCalcWinClient.CalcService.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PerformOperation(string operandA, string operandB, char op) {
            return base.Channel.PerformOperation(operandA, operandB, op);
        }
        
        public System.Threading.Tasks.Task<string> PerformOperationAsync(string operandA, string operandB, char op) {
            return base.Channel.PerformOperationAsync(operandA, operandB, op);
        }
    }
}
